$ErrorActionPreference = 'Stop'

# Load current recipes
$recipesPath = "locale\ko\recipes.json"
$recipes = Get-Content $recipesPath -Raw -Encoding UTF8 | ConvertFrom-Json

# Load items for reference
$items = Get-Content "locale\ko\items.json" -Raw -Encoding UTF8 | ConvertFrom-Json

# Additional recipe-specific translations
$recipeTranslations = @{
    "active-provider-chest" = "능동 공급 상자"
    "advanced-oil-processing" = "고급 석유 처리"
    "arithmetic-combinator" = "산술 조합기"
    "artillery-turret" = "포병 포탑"
    "artillery-wagon" = "포병 화차"
    "assembling-machine-1" = "조립 기계 1"
    "assembling-machine-2" = "조립 기계 2"
    "assembling-machine-3" = "조립 기계 3"
    "atomic-bomb" = "원자 폭탄"
    "automation-science-pack" = "자동화 과학 팩"
    "barrel" = "배럴"
    "basic-oil-processing" = "기초 석유 처리"
    "battery-equipment" = "배터리 장비"
    "battery-mk2-equipment" = "배터리 MK2 장비"
    "beacon" = "신호기"
    "belt-immunity-equipment" = "벨트 면역 장비"
    "big-electric-pole" = "대형 전봇대"
    "boiler" = "보일러"
    "buffer-chest" = "버퍼 상자"
    "bulk-inserter" = "대량 인서터"
    "burner-inserter" = "연소 인서터"
    "burner-mining-drill" = "연소 채굴 드릴"
    "cannon-shell" = "대포 포탄"
    "car" = "자동차"
    "cargo-landing-pad" = "화물 착륙장"
    "cargo-wagon" = "화물 화차"
    "centrifuge" = "원심분리기"
    "chemical-plant" = "화학 공장"
    "chemical-science-pack" = "화학 과학 팩"
    "cliff-explosives" = "절벽 폭발물"
    "cluster-grenade" = "집속 수류탄"
    "coal-liquefaction" = "석탄 액화"
    "combat-shotgun" = "전투 산탄총"
    "concrete" = "콘크리트"
    "constant-combinator" = "상수 조합기"
    "construction-robot" = "건설 로봇"
    "decider-combinator" = "결정 조합기"
    "defender-capsule" = "방어 캡슐"
    "destroyer-capsule" = "파괴자 캡슐"
    "discharge-defense-equipment" = "방전 방어 장비"
    "display-panel" = "디스플레이 패널"
    "distractor-capsule" = "교란 캡슐"
    "efficiency-module" = "효율 모듈"
    "efficiency-module-2" = "효율 모듈 2"
    "efficiency-module-3" = "효율 모듈 3"
    "electric-furnace" = "전기 용광로"
    "electric-mining-drill" = "전기 채굴 드릴"
    "energy-shield-equipment" = "에너지 보호막 장비"
    "energy-shield-mk2-equipment" = "에너지 보호막 MK2 장비"
    "engine-unit" = "엔진 유닛"
    "exoskeleton-equipment" = "외골격 장비"
    "explosive-cannon-shell" = "폭발 대포 포탄"
    "explosive-rocket" = "폭발 로켓"
    "explosive-uranium-cannon-shell" = "폭발 우라늄 대포 포탄"
    "express-loader" = "고속 로더"
    "express-splitter" = "고속 분배기"
    "express-transport-belt" = "고속 컨베이어 벨트"
    "express-underground-belt" = "고속 지하 벨트"
    "fast-inserter" = "빠른 인서터"
    "fast-loader" = "빠른 로더"
    "fast-splitter" = "빠른 분배기"
    "fast-transport-belt" = "빠른 컨베이어 벨트"
    "fast-underground-belt" = "빠른 지하 벨트"
    "firearm-magazine" = "화기 탄창"
    "fission-reactor-equipment" = "핵분열 반응로 장비"
    "flamethrower" = "화염방사기"
    "flamethrower-ammo" = "화염방사기 탄약"
    "flamethrower-turret" = "화염방사 포탑"
    "fluid-wagon" = "액체 화차"
    "gate" = "게이트"
    "grenade" = "수류탄"
    "gun-turret" = "기관총 포탑"
    "hazard-concrete" = "위험 표시 콘크리트"
    "heavy-armor" = "중장갑"
    "heavy-oil-cracking" = "중유 분해"
    "iron-chest" = "철 상자"
    "kovarex-enrichment-process" = "코바렉스 농축 공정"
    "lab" = "연구소"
    "landfill" = "매립지"
    "land-mine" = "지뢰"
    "laser-turret" = "레이저 포탑"
    "light-armor" = "경장갑"
    "light-oil-cracking" = "경유 분해"
    "loader" = "로더"
    "locomotive" = "기관차"
    "logistic-robot" = "물류 로봇"
    "logistic-science-pack" = "물류 과학 팩"
    "long-handed-inserter" = "긴팔 인서터"
    "low-density-structure" = "저밀도 구조물"
    "lubricant" = "윤활유"
    "medium-electric-pole" = "중형 전봇대"
    "military-science-pack" = "군사 과학 팩"
    "modular-armor" = "모듈식 장갑"
    "night-vision-equipment" = "야간 투시경 장비"
    "nuclear-fuel" = "핵연료"
    "nuclear-fuel-reprocessing" = "핵연료 재처리"
    "nuclear-reactor" = "원자로"
    "offshore-pump" = "해안 펌프"
    "oil-refinery" = "정유 공장"
    "passive-provider-chest" = "수동 공급 상자"
    "personal-laser-defense-equipment" = "개인 레이저 방어 장비"
    "personal-roboport-equipment" = "개인 로보포트 장비"
    "personal-roboport-mk2-equipment" = "개인 로보포트 MK2 장비"
    "piercing-rounds-magazine" = "관통탄 탄창"
    "piercing-shotgun-shell" = "관통 산탄 탄약"
    "pipe" = "파이프"
    "pipe-to-ground" = "지하 파이프"
    "pistol" = "권총"
    "plastic-bar" = "플라스틱"
    "poison-capsule" = "독 캡슐"
    "power-armor" = "파워 아머"
    "power-armor-mk2" = "파워 아머 MK2"
    "power-switch" = "전력 스위치"
    "processing-unit" = "처리 유닛"
    "production-science-pack" = "생산 과학 팩"
    "productivity-module" = "생산성 모듈"
    "productivity-module-2" = "생산성 모듈 2"
    "productivity-module-3" = "생산성 모듈 3"
    "programmable-speaker" = "프로그래밍 가능 스피커"
    "pump" = "펌프"
    "pumpjack" = "펌프잭"
    "radar" = "레이더"
    "rail" = "철로"
    "rail-chain-signal" = "철로 연쇄 신호기"
    "rail-signal" = "철로 신호기"
    "red-wire" = "적색 전선"
    "refined-concrete" = "정제 콘크리트"
    "refined-hazard-concrete" = "정제 위험 표시 콘크리트"
    "repair-pack" = "수리 팩"
    "requester-chest" = "요청 상자"
    "roboport" = "로보포트"
    "rocket" = "로켓"
    "rocket-control-unit" = "로켓 제어 장치"
    "rocket-fuel" = "로켓 연료"
    "rocket-launcher" = "로켓 발사기"
    "rocket-part" = "로켓 부품"
    "rocket-silo" = "로켓 사일로"
    "satellite" = "위성"
    "selector-combinator" = "선택 조합기"
    "shotgun" = "산탄총"
    "shotgun-shell" = "산탄 탄약"
    "slowdown-capsule" = "둔화 캡슐"
    "small-electric-pole" = "소형 전봇대"
    "small-lamp" = "소형 전등"
    "solar-panel" = "태양 전지판"
    "solar-panel-equipment" = "태양 전지판 장비"
    "solid-fuel" = "고체 연료"
    "solid-fuel-from-heavy-oil" = "고체 연료 (중유)"
    "solid-fuel-from-light-oil" = "고체 연료 (경유)"
    "solid-fuel-from-petroleum-gas" = "고체 연료 (석유 가스)"
    "space-science-pack" = "우주 과학 팩"
    "speed-module" = "속도 모듈"
    "speed-module-2" = "속도 모듈 2"
    "speed-module-3" = "속도 모듈 3"
    "spidertron" = "스파이더트론"
    "spidertron-remote" = "스파이더트론 원격 조종"
    "splitter" = "분배기"
    "steam-engine" = "증기 기관"
    "steam-turbine" = "증기 터빈"
    "steel-chest" = "강철 상자"
    "steel-furnace" = "강철 용광로"
    "steel-plate" = "강철 판"
    "stone-brick" = "석재 벽돌"
    "stone-furnace" = "돌 용광로"
    "stone-wall" = "돌 벽"
    "storage-chest" = "저장 상자"
    "storage-tank" = "저장 탱크"
    "submachine-gun" = "기관단총"
    "substation" = "변전소"
    "sulfur" = "황"
    "sulfuric-acid" = "황산"
    "tank" = "탱크"
    "tank-cannon" = "탱크 대포"
    "tank-flamethrower" = "탱크 화염방사기"
    "tank-machine-gun" = "탱크 기관총"
    "train-stop" = "기차역"
    "transport-belt" = "컨베이어 벨트"
    "underground-belt" = "지하 벨트"
    "uranium-cannon-shell" = "우라늄 대포 포탄"
    "uranium-fuel-cell" = "우라늄 연료봉"
    "uranium-processing" = "우라늄 처리"
    "uranium-rounds-magazine" = "우라늄 탄창"
    "utility-science-pack" = "유틸리티 과학 팩"
    "vehicle-machine-gun" = "차량 기관총"
    "wooden-chest" = "나무 상자"
}

# Krastorio2 translations
$kr2Translations = @{
    "kr-advanced-fuel" = "고급 연료"
    "kr-advanced-tech-card" = "고급 기술 카드"
    "kr-ai-core" = "AI 코어"
    "kr-air-cleaning" = "공기 정화"
    "kr-ammonia" = "암모니아"
    "kr-atmosphere-condensation" = "대기 응축"
    "kr-automation-core" = "자동화 코어"
    "kr-basic-tech-card" = "기초 기술 카드"
    "kr-bio-fuel" = "바이오 연료"
    "kr-biomass" = "바이오매스"
    "kr-biomethanol" = "바이오메탄올"
    "kr-charged-antimatter-fuel-cell" = "충전된 반물질 연료 셀"
    "kr-charged-matter-stabilizer" = "충전된 물질 안정기"
    "kr-chlorine" = "염소"
    "kr-coke" = "코크스"
    "kr-dt-fuel" = "DT 연료"
    "kr-dt-fuel-cell" = "DT 연료 셀"
    "kr-electronic-components" = "전자 부품"
    "kr-empty-antimatter-fuel-cell" = "빈 반물질 연료 셀"
    "kr-empty-dt-fuel-cell" = "빈 DT 연료 셀"
    "kr-energy-control-unit" = "에너지 제어 장치"
    "kr-enriched-copper" = "농축 구리"
    "kr-enriched-iron" = "농축 철"
    "kr-enriched-rare-metals" = "농축 희귀 금속"
    "kr-fertilizer" = "비료"
    "kr-fuel" = "연료"
    "kr-glass" = "유리"
    "kr-heavy-water" = "중수"
    "kr-hydrogen" = "수소"
    "kr-hydrogen-chloride" = "염화수소"
    "kr-imersium-beam" = "이머시움 빔"
    "kr-imersium-gear-wheel" = "이머시움 톱니바퀴"
    "kr-imersium-plate" = "이머시움 판"
    "kr-imersite-crystal" = "이머사이트 결정"
    "kr-imersite-powder" = "이머사이트 가루"
    "kr-inserter-parts" = "인서터 부품"
    "kr-iron-beam" = "철 빔"
    "kr-lithium" = "리튬"
    "kr-lithium-chloride" = "염화 리튬"
    "kr-lithium-sulfur-battery" = "리튬 황 배터리"
    "kr-matter" = "물질"
    "kr-matter-assembling" = "물질 조립"
    "kr-matter-cube" = "물질 큐브"
    "kr-matter-stabilizer" = "물질 안정기"
    "kr-matter-tech-card" = "물질 기술 카드"
    "kr-mineral-water" = "광천수"
    "kr-nitric-acid" = "질산"
    "kr-nitrogen" = "질소"
    "kr-oxygen" = "산소"
    "kr-pollution-filter" = "오염 필터"
    "kr-quartz" = "석영"
    "kr-rare-metals" = "희귀 금속"
    "kr-sand" = "모래"
    "kr-silicon" = "실리콘"
    "kr-singularity-tech-card" = "특이점 기술 카드"
    "kr-steel-beam" = "강철 빔"
    "kr-steel-gear-wheel" = "강철 톱니바퀴"
    "kr-tritium" = "삼중수소"
    "kr-vc-a" = "바이러스 캡슐 A"
    "kr-vc-b" = "바이러스 캡슐 B"
    "kr-vc-c" = "바이러스 캡슐 C"
}

# Merge all translations
$allTranslations = @{}
foreach ($key in $recipeTranslations.Keys) {
    $allTranslations[$key] = $recipeTranslations[$key]
}
foreach ($key in $kr2Translations.Keys) {
    $allTranslations[$key] = $kr2Translations[$key]
}

# Build new recipes object
$newRecipes = [ordered]@{}
foreach ($prop in $recipes.PSObject.Properties | Sort-Object Name) {
    $key = $prop.Name
    $currentValue = $prop.Value
    
    # Priority: keep existing translations, then use recipe translations, then use item translations, then keep original
    if ($currentValue -ne $key) {
        # Already translated, keep it
        $newRecipes[$key] = $currentValue
    } elseif ($allTranslations.ContainsKey($key)) {
        # Use recipe-specific translation
        $newRecipes[$key] = $allTranslations[$key]
    } else {
        # Try to get from items
        $itemValue = $items.PSObject.Properties | Where-Object { $_.Name -eq $key } | Select-Object -ExpandProperty Value -ErrorAction SilentlyContinue
        if ($itemValue -and $itemValue -ne $key) {
            $newRecipes[$key] = $itemValue
        } else {
            # Keep original
            $newRecipes[$key] = $currentValue
        }
    }
}

# Save
$newRecipes | ConvertTo-Json -Depth 10 | Out-File $recipesPath -Encoding UTF8 -Force

$translated = ($newRecipes.GetEnumerator() | Where-Object { $_.Value -ne $_.Key }).Count
$total = $newRecipes.Count

Write-Host "Translation complete!"
Write-Host "Translated: $translated / $total recipes"
